name: Run Python Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run tests
        working-directory: Querio  # Set the working directory to the 'tests' directory
        run: python test.py  # Update the path to your test script as needed
